name: AWS ECR Push Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ecommerce-test

jobs:
  ecr-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::743320495203:role/GitHubActions-Ecommerce
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      - name: Tag Docker image
        run: |
          docker tag \
            $ECR_REPOSITORY:latest \
            743320495203.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Push Docker image
        run: |
          docker push \
            743320495203.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:latest

      - name: Verify image
        run: |
          aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --region $AWS_REGION
