name: AWS OIDC Debug

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-debug:
    runs-on: ubuntu-latest

    steps:
      - name: OIDC Debugger
        uses: github/actions-oidc-debugger@main
